# Generated by Django 5.2.3 on 2025-06-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('hora_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
