# Generated by Django 5.2.3 on 2025-06-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='descrição',
            field=models.CharField(default='no description', max_length=500),
            preserve_default=False,
        ),
    ]
