# Generated by Django 5.2.3 on 2025-06-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_genero_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.ManyToManyField(to='core.genero'),
        ),
    ]
